### ISSUE TITLE
Automation create json

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#81]
Hello!
Thanks for rpmvenv!
May be automation create json?
For example, create rpm from CLI rpmvenv without created json by hand.
rpmvenv --name "some-rpm-package-name" --version "1.2.3"

rpmvenv go to pypi.org and get information from site. After rpmvenv create json and build rpm.

**Comment by kevinconway** [comment]
I think the easiest thing to do is:

```bash
echo "{}" > conf.json && rpmvenv \
  conf.json \
  --core_name="some-rpm-package-name" \
  --core_version="1.2.3" \
  --core_license="MIT" \
  --python_venv_path="/path/for/install"
```

This will create an empty JSON file and use it with the `rpmvenv` command. You can set all options you need using the CLI or environment variables. The CLI pattern is `--<extension>_<option>`. Examples: `--blocks_desc` and `--file_permissions_users`. The environment variable pattern is `RPMVENV_<EXTENSION>_<OPTION>`. Examples: `RPMVENV_BLOCKS_DESC` and `RPMVENV_FILE_PERMISSIONS_USERS`.

**Comment by patsevanton** [comment]
I try, but get error:

```
pip install --user rpmvenv

mkdir /tmp/msgpack

echo "{}" > conf.json && rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --python_venv_path="/tmp/msgpack"
Traceback (most recent call last):
  File "/home/centos/.local/bin/rpmvenv", line 9, in <module>
    load_entry_point('rpmvenv==0.23.0', 'console_scripts', 'rpmvenv')()
  File "/home/centos/.local/lib/python2.7/site-packages/rpmvenv/cli.py", line 142, in main
    args['verbose'],
  File "/home/centos/.local/lib/python2.7/site-packages/rpmvenv/cli.py", line 77, in generate_rpm
    pkg = rpmbuild.build(specfile=specfile, top=top, verbose=verbose)
  File "/home/centos/.local/lib/python2.7/site-packages/rpmvenv/rpmbuild.py", line 161, in build
    quiet_popen(cmd)
  File "/home/centos/.local/lib/python2.7/site-packages/rpmvenv/rpmbuild.py", line 122, in quiet_popen
    stderr=subprocess.PIPE,
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by patsevanton** [comment]
```yum install -y rpmdevtools
```
