### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#84]
Thanks for rpmvenv.
I try build rpm for python package on CentOS 7.

```
sudo yum -y install epel-release rpmdevtools
sudo yum -y install python2-pip
pip install --user rpmvenv
echo "{}" > conf.json && rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --core_summary="Package created by rpmvenv" --python_venv_path="/tmp/msgpack"
```

Error:
```
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenvhQBuQb' /tmp/rpmvenvhQBuQb/SOURCES/package.spec.
Traceback (most recent call last):
  File "/home/centos/.local/bin/rpmvenv", line 9, in <module>
    load_entry_point('rpmvenv==0.23.0', 'console_scripts', 'rpmvenv')()
  File "/home/centos/.local/lib/python2.7/site-packages/rpmvenv/cli.py", line 160, in main
    os.linesep,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

**Comment by patsevanton** [comment]
```
sudo yum -y install epel-release rpmdevtools
sudo yum -y install python3-pip
pip3 install --user rpmvenv
echo "{}" > conf.json && rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --core_summary="Package created by rpmvenv" --python_venv_path="/tmp/msgpack"
```

Error:
```
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenvrtvexcbh' /tmp/rpmvenvrtvexcbh/SOURCES/package.spec.
The stderr was: b'\xd0\xbe\xd1\x88\xd0\xb8\xd0\xb1\xd0\xba\xd0\xb0: \xd0\x9f\xd0\xb0\xd0\xba\xd0\xb5\xd1\x82 \xd0\xbd\xd0\xb5 \xd0\xb8\xd0\xbc\xd0\xb5\xd0\xb5\xd1\x82 %description: msgpack\n'.
The stdout was: .
```

**Comment by kevinconway** [comment]
CentOS has a default encoding of ASCII. You can use an environment variable to force UTF-8:

```bash
echo "{}" > conf.json && \
LC_ALL=en_US.UTF-8 rpmvenv conf.json \
  --core_name="msgpack" \
  --core_version="0.6.1" \
  --core_license="MIT" \
  --core_summary="Package created by rpmvenv" \
  --python_venv_path="/tmp/msgpack"
```

This is the issue I mention in https://github.com/kevinconway/rpmvenv#note-unicode.

**Comment by patsevanton** [comment]
I am sorry. I can not found option for CLI

```
echo "{}" > conf.json && LC_ALL=en_US.UTF-8 rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --core_summary="msgpack" --python_venv_path="/tmp/msgpack"
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenv7pYnKc' /tmp/rpmvenv7pYnKc/SOURCES/package.spec.
The stderr was: error: Package has no %description: msgpack
.
The stdout was: .
```

**Comment by kevinconway** [comment]
You need to add the `--blocks_desc` flag to set a description. It is not well documented by `rpm` but you must include `summary` _and_ `description` together when using the current version of `rpm`.

If you see `The rpmbuild command was: rpmbuild` in the logs then the `stderr` text is from the actual `rpm` tool. You can copy the `rpmbuild` command and run it to see more error text. You can also add `--verbose` to get much more output.

I will close this because the `ascii` issue is fixed. Please open more issues if you continue having trouble.
