### ISSUE TITLE
Permission not apply

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#99]
Have user and group airflow 
```
[airflow@airflow ~]$ id
uid=1000(airflow) gid=1000(airflow) groups=1000(airflow)
```
Install package

```
sudo yum install -y python3-devel python3-pip gcc gcc-c++ cyrus-sasl-devel krb5-devel
sudo yum -y install epel-release rpmdevtools wget
```

Install rpmvenv
```
pip3 install --user rpmvenv
pip3 install --user virtualenv
```
Create requirements.txt
Create rpm
```
echo "{}" > conf.json && \
LC_ALL=en_US.UTF-8 rpmvenv conf.json \
--core_name="apache-airflow" \
--core_version="1.10.12" \
--core_license="ASL 2.0" \
--core_summary="apache-airflow" \
--extensions_enabled="blocks,python_venv" \
--python_venv_name="apache-airflow" \
--python_venv_path="/home/airflow" \
--blocks_desc="apache-airflow" \
--python_venv_require_setup_py="false" \
--file_permissions_user="airflow" \
--file_permissions_group="airflow"
```

Install rpm. After install rpm.

```
[airflow@airflow ~]$ ls -l /home/airflow/apache-airflow
total 20
-rw-r--r-- 1 root root 11340 Jan 25 10:09 LICENSE
drwxr-xr-x 3 root root  4096 Jan 25 10:20 bin
drwxr-xr-x 3 root root    31 Jan 25 10:20 etc
drwxr-xr-x 3 root root    23 Jan 25 10:20 lib
drwxr-xr-x 3 root root    23 Jan 25 10:21 lib64
-rw-r--r-- 1 root root   201 Jan 25 10:07 pyvenv.cfg
```

How change permission?
Thanks!

**Comment by kevinconway** [comment]
It's not working because you did not enable the `file_permissions` plugin. `--extensions_enabled="blocks,python_venv" \` needs to be `--extensions_enabled="blocks,python_venv,file_permissions" \`

**Comment by patsevanton** [comment]
Thanks!
I use `--extensions_enabled="blocks,python_venv,file_permissions"`

```
sudo yum install -y apache-airflow-1.10.12-1.x86_64.rpm
sudo yum install -y python3-pip
pip3 install --user virtualenv
source /home/airflow/apache-airflow/bin/activate
airflow initdb
```

Error
```
Traceback (most recent call last):
  File "//home/airflow/apache-airflow/lib64/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "//home/airflow/apache-airflow/lib64/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "//home/airflow/apache-airflow/lib64/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//home/airflow/apache-airflow/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "//home/airflow/apache-airflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 80, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "//home/airflow/apache-airflow/lib/python3.6/site-packages/airflow/www/app.py", line 38, in <module>
    from airflow.www.blueprints import routes
  File "//home/airflow/apache-airflow/lib/python3.6/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "//home/airflow/apache-airflow/lib/python3.6/site-packages/airflow/www/utils.py", line 48, in <module>
    from airflow.utils.json import AirflowJsonEncoder
  File "//home/airflow/apache-airflow/lib/python3.6/site-packages/airflow/utils/json.py", line 27, in <module>
    import numpy as np
  File "//home/airflow/apache-airflow/lib64/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "//home/airflow/apache-airflow/lib64/python3.6/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "//home/airflow/apache-airflow/bin/python"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned
```

Hm. I try pack directory. Thanks!

**Comment by kevinconway** [comment]
@patsevanton This type of error seems similar to previous issues with manylinux (https://github.com/kevinconway/rpmvenv#note-manylinux). My only advice is to try settings the `python_venv.strip_binaries` value to `False` and setting the `QA_SKIP_BUILD_ROOT=1` environment variable when you build the RPM. That will prevent rpmvenv from modifying the compiled C binaries. If that does not solve it then I am not sure what else to try. C extensions like numpy are difficult to package.

**Comment by patsevanton** [comment]
Work!! Thanks!

```
sudo sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config
sudo reboot
sudo yum install -y python3-devel python3-pip gcc gcc-c++ cyrus-sasl-devel krb5-devel
sudo yum -y install epel-release rpmdevtools wget
sudo yum install -y python3-devel python3-pip gcc gcc-c++ cyrus-sasl-devel krb5-devel
sudo yum -y install epel-release rpmdevtools wget
vi requirements.txt
echo "{}" > conf.json && LC_ALL=en_US.UTF-8 rpmvenv conf.json --core_name="apache-airflow" --core_version="1.10.12" --core_license="ASL 2.0" --core_summary="apache-airflow" --extensions_enabled="blocks,python_venv" --python_venv_name="apache-airflow" --python_venv_path="/home/airflow" --python_venv_strip_binaries="false" --blocks_desc="apache-airflow" --python_venv_require_setup_py="false" --file_permissions_user="airflow" --file_permissions_group="airflow"
sudo yum install -y apache-airflow-1.10.12-1.x86_64.rpm
sudo yum install -y python3-pip
pip3 install --user virtualenv
pip3 install --user rpmvenv
pip3 install --user virtualenv
source /home/airflow/apache-airflow/bin/activate
airflow initdb
airflow webserver -p 8080
deactivate
```
